# Generated by Django 4.1.7 on 2023-04-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_images')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='home.movie')),
            ],
        ),
    ]
