# Generated by Django 4.1.7 on 2023-04-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_movie_image_movieimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
