# Generated by Django 4.1.7 on 2023-04-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_movie_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='mov_id',
        ),
    ]
