# Generated by Django 4.1.7 on 2023-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_movieimage_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
